name: din
description: An open source Quran reader using material design and Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0-beta

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:  ^4.6.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.5
  flutter_markdown: ^0.6.12
  package_info_plus: ^1.4.3+1
  http: ^0.13.5
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  geolocator: ^9.0.2
  flutter_local_notifications: ^12.0.4
  flutter_svg: ^1.1.6
  sensors_plus: ^2.0.1
  adhan_dart: ^1.0.8
  intl: ^0.18.0
  scroll_to_index: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/
    - assets/json/
    - assets/json/quran_editions/
    - assets/json/quran_editions/$.original/
    - assets/json/quran_editions/$.transliteration/
    - assets/json/quran_editions/en.quran-in-english/
    - assets/json/hadith/bukhari/
    - assets/json/hadith/hisnulmuslim/

#  fonts:
#
#    - family: NotoSansArabic                                  # sans
#      fonts:
#        - asset: assets/fonts/NotoSansArabic-Regular.ttf
#
#    - family: NotoNaskhArabic                                 # sans-serif
#      fonts:
#        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
#
#    - family: NotoNastaliqUrdu                                # serif
#      fonts:
#        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
#    
#    - family: NotoKufiArabic                                # kufi
#      fonts:
#        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
